### ISSUE TITLE
Documentation for using OR operation in search filter

### ISSUE THREAD

**Issue by mahirjain25** [kumuluz/kumuluzee-rest#17]
Hi Team, 

I have a use case where I need to make an OR query in my search filter. I noticed a PR (#11) has been merged for the same by @osbeorn 

I essentially want to create a query that performs the following operation: inputValue = (field1.value OR field2.value)

It would be great if you could give an example for the filter for such a use case. Further, just raising this issue to highlight the need for documentation for some of the recent changes that have been merged!

**Comment by osbeorn** [comment]
Hi,

the PR contains a wrong commit message and does not contain any improvements to query parsing and the public API. The enchanced query parsing functionality is still a WIP and can be found on [this branch](https://github.com/kumuluz/kumuluzee-rest/tree/feature/enhanced-filter-parsing).

I will update the main documentation when the feature is finalised and near completion.

**Comment by mahirjain25** [comment]
Thanks for the clarification! 
Would it be possible for you to provide a rough approximation as to when this feature will be complete and available to use?

**Comment by MBJuric** [comment]
Expect this to be ready in two to three weeks. Implementation is mostly ready, we need to test and release it. 
Best regards.

**Comment by mahirjain25** [comment]
Great! Thanks again!

**Comment by osbeorn** [comment]
A new version has been [released](https://github.com/kumuluz/kumuluzee-rest/releases/tag/v1.5.0). Check the README for more information on the improved filtering feature.
