### ISSUE TITLE
Would like work on other containers?

### ISSUE THREAD

**Issue by mwnorman** [kumuluz/kumuluzee-rest#4]
Say Payara/Glassfish for example?

**Comment by osbeorn** [comment]
I don't understand your question. Did you mean if kumuluzee-rest would work on Payara/Glassfish?

**Comment by mwnorman** [comment]
Yes ... meant to say 'Would it likely work on other containers?'

**Comment by osbeorn** [comment]
I haven't tested it myself, but yes, it should work as it it not dependent on KumuluzEE.
